version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ex2_gs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    image: albertasatdocker/ground-station-website:dev-latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ex2_gs
    volumes:
      - ./:/home/ex2_ground_station_website
    entrypoint: ./update.sh
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - db
  webpack:
    image: node:lts-alpine
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/groundstation/static/
    command: ["npm", "run", "watch"]
    depends_on:
      - web
    deploy:
      restart_policy:
        conidition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
