version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=ex2_gs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    image: albertasatdocker/ground-station-website:dev-latest
    expose:
      - 5000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ex2_gs
    volumes:
      - ./:/home/ex2_ground_station_website
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
