"""empty message

Revision ID: c4c736ff544f
Revises: ffaf3459d809
Create Date: 2019-10-05 14:41:24.493382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c736ff544f'
down_revision = 'ffaf3459d809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satelliteMode', sa.String(length=32), nullable=True),
    sa.Column('batteryVoltage', sa.Float(), nullable=True),
    sa.Column('currentIn', sa.Float(), nullable=True),
    sa.Column('currentOut', sa.Float(), nullable=True),
    sa.Column('noMCUResets', sa.Integer(), nullable=True),
    sa.Column('lastBeaconTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satellite_model')
    # ### end Alembic commands ###
