name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  dev-image:
    name: Build the website dev image
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
