name: run tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
          architecture: 'x64'
      
      - name: install pip dependencies
        run: python -m pip install -r requirements.txt

      - name: run unit tests
        run: python manage.py test
        env: # !!! WARNING: EXPOSED SECRETS !!!
          FLASK_APP: groundstation/__init__.py
          FLASK_ENV: development
          APP_SETTINGS: groundstation.config.TestingConfig
          SECRET_KEY: "\xffY\x8dG\xfbu\x96S\x86\xdfu\x98\xe8S\x9f\x0e\xc6\xde\xb6$\xab:\x9d\x8b"
