name: Run tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install pip dependencies
        run: python -m pip install -r requirements.txt

      - name: Run unit tests
        run: python manage.py test
        env: # !!! WARNING: EXPOSED SECRETS !!!
          FLASK_APP: groundstation/__init__.py
          FLASK_ENV: development
          APP_SETTINGS: groundstation.config.TestingConfig
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
